#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Gustavo Franco <gufranco@users.noreply.github.com>
# SPDX-License-Identifier: MIT

import subprocess
import sys

CHECK = [sys.executable, "-m", "tools.commit_message", "--file"]


def main() -> int:
    return subprocess.run([*CHECK, sys.argv[1]], check=False).returncode


if __name__ == "__main__":
    sys.exit(main())
