version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
    labels:
      - dependencies
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: build
    labels:
      - dependencies
    groups:
      base-image:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /docker
    schedule:
      interval: weekly
    commit-message:
      prefix: build
    labels:
      - dependencies
    groups:
      python-tools:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: build
    labels:
      - dependencies
    ignore:
      - dependency-name: conventional-changelog-conventionalcommits
        update-types:
          - version-update:semver-major
    groups:
      release-tooling:
        patterns:
          - "*"
