#ifndef FDSWRITEUNLOCK_BOARD_H
#define FDSWRITEUNLOCK_BOARD_H

enum {
    PIN_WRITE_DATA = 3,
    PIN_WRITE_GATE_N = 4,
    PIN_WRITE_PROTECT_N = 5,
    PIN_READY_N = 6,
    PIN_HEAD1 = 7,
    PIN_HEAD2 = 8,
    PIN_ACTIVITY_LED = 25
};

#define WRITE_STAGE_PIO pio0
#define WRITE_STAGE_GPIO_FUNCTION GPIO_FUNC_PIO0

#define WRITE_CONDITION_PINS ((1u << PIN_WRITE_GATE_N) | (1u << PIN_WRITE_PROTECT_N) | (1u << PIN_READY_N))

#endif
